<?php

namespace BaklavaBorekBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function getPie(){
        return $this->createQueryBuilder("pie")
            ->select(array("pr.name"))
            ->innerJoin('BaklavaBorekBundle\Entity\Product', 'pr', 'WITH', 'pr.id = pie.product')
            ->addSelect("COUNT(pie.product) as value")
            ->groupBy("pie.product")
            ->getQuery()
            ->getResult();
    }
}
