<?php

namespace BaklavaBorekBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function get_Pie(){
        return $this->createQueryBuilder("pie")
            ->select(array("pie", "pr.name"))
            ->innerJoin("BaklavaBorekBundle\Entity\Product", "pr")
            ->addSelect("COUNT(pie.product) as kac_tane")
            ->where("pr.id = pie.product")
            ->groupBy("pie.product")
            ->getQuery()
            ->getResult();
    }
}
