<?php

namespace BaklavaBorekBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MailDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailDetailRepository extends EntityRepository
{
}
